include(RunCMake)

run_cmake(NotFoundContent)
run_cmake(DebugIncludes)
run_cmake(TID-bad-target)
if (NOT SOURCE_IN_INSTALL_PREFIX)
  run_cmake(SourceDirectoryInInterface)
endif()
if (NOT BUILD_IN_INSTALL_PREFIX)
  run_cmake(BinaryDirectoryInInterface)
endif()
run_cmake(RelativePathInInterface)
run_cmake(ImportedTarget)
run_cmake(RelativePathInGenex)
run_cmake(CMP0021)
run_cmake(install_config)
run_cmake(incomplete-genex)
run_cmake(export-NOWARN)
