include(RunCMake)

run_cmake(not_enough_args)
run_cmake(alias_target)
run_cmake(utility_target)
run_cmake(invalid_args)
run_cmake(invalid_args_on_interface)
run_cmake(imported_target)
run_cmake(no_target)
run_cmake(not_a_cxx_feature)
run_cmake(no_matching_cxx_feature)
if (NOT CMAKE_GENERATOR MATCHES "Borland")
  set(RunCMake_TEST_OPTIONS "-DCMAKE_CXX_COMPILER_ID=UnknownCompiler")
  run_cmake(unknown_compiler)
endif()
